apiVersion: v1
kind: Service
metadata:
  name: messaging
spec:
  selector:
    tier: msg    
  ports:          
  - name: messaging-service    
    protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
