apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
spec:
  containers:
  - command:
      - sleep
      - "1000"
    image: busybox
    name: busybox
    
    
   #### second choise ###

apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","1000"]
