apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: hr-web-app
        image: kodekloud/webapp-color
        ports:
        - containerPort: 80
