metadata:
  name: hare
spec:
  selector:
    matchLabels:
      app: hare
  replicas: 2
  template:
    metadata:
      labels:
        app: hare
        deploy: green-blue
    spec:
      containers:
        - name: animals:hare
        image: supergiantkir/animals:hare
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Deployment
metadata:
  name: green
spec:
  selector:
    matchLabels:
      app: green
  replicas: 1
  template:
    metadata:
      labels:
        app: green
        deploy: green-blue
    spec:
      containers:
        - name: animals:hare
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
