Parameters:
  EnvironmentName:
    Description: Environment Name
    Type: String
    Default: development
    AllowedValues: 
      - development
      - production
    ConstraintDescription: must be development or production

Mappings:
  EnvironmentToInstanceType:
    development:
      instanceType: t2.micro
    # we want a bigger instance type in production
    production:
      instanceType: t2.small

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref 'EnvironmentName', instanceType]
      # Note we use the pseudo parameter AWS::Region
      ImageId: ami-096800910c1b781ba
